<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6ef507829fa1d1ced9b2653ca24f35ec
{
    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jankx\\Extensions\\Travel\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jankx\\Extensions\\Travel\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6ef507829fa1d1ced9b2653ca24f35ec::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6ef507829fa1d1ced9b2653ca24f35ec::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6ef507829fa1d1ced9b2653ca24f35ec::$classMap;

        }, null, ClassLoader::class);
    }
}
